### ISSUE TITLE
Do you have a blog post for this with explaination step by step?

### ISSUE THREAD

**Issue by wise-ubuntu** [ShahriyarR/hexagonal-fastapi-jobboard#1]

**Comment by ShahriyarR** [comment]
Unfortunately not for this repo.

I have 3 series of intro using Flask based on:

https://github.com/ShahriyarR/hexagonal-flask-blog-tutorial

Medium articles:

https://blog.devgenius.io/flask-blog-tutorial-with-hexagonal-architecture-part-1-6446e7e9aaaa
https://blog.devgenius.io/flask-blog-tutorial-with-hexagonal-architecture-part-2-8930ca009c27
https://blog.devgenius.io/flask-blog-tutorial-with-hexagonal-architecture-part-3-9a265f0c4b95


This repo is more advance form and need more explanation. In the future maybe I will record some course based on this repo.
